
title: Alejandro F Queiruga
email: af(last name) (at) lbl (dot) gov
description: >- 
  LaTeX files and handwritten notebooks end up in an ever growing
  graveyard of scientific work. Now I'm just publishing all of my
  work incrementally, like how science is supposed to work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  afqueiruga
bitbucket_username: afqueiruga

# Build settings
markdown: kramdown
theme: minima #jekyll-theme-minimal
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
