
title: Alejandro F Queiruga
email: (first name) (dot) (last name) (at) gmail (dot) com
description: >- 
  Software engineer and researcher.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://queiruga.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  afqueiruga
bitbucket_username: afqueiruga

# Build settings
markdown: kramdown
theme: minima #jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-org
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
